name: PR Merged Notification

on:
  pull_request:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Print message for users
        run: echo "Thanks for contributing"
