name: PR Merged Notification

on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Print message for users
        run: echo "Thanks for contributing"
